[flavor]
name = "writerdeck"
description = "SolarOS build for distraction free writing and reading."

[packages]
system = true
expansions = false
maintenance_apps = true
maintenance_jobs = true
hardware_jobs = false
audio = false
net = true
agent = false
media = false
games = false
python = false
lua = false
writing = true
utils = false
