#!/usr/bin/env python3
"""Generate the package-gated SolarOS manual registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import tomllib


ID_RE = re.compile(r"^[a-z0-9][a-z0-9_.-]*$")


def package_macro(package: str) -> str:
    return "SOLAR_OS_PACKAGE_" + re.sub(r"[^A-Za-z0-9]", "_", package).upper()


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def default_body(page: dict[str, object]) -> str:
    return (
        f"NAME\n    {page['id']} - {page['summary']}\n\n"
        f"SECTION\n    {page['section']}\n\n"
        f"DESCRIPTION\n    {str(page['contract']).replace(chr(10), chr(10) + '    ')}\n"
    )


def load_pages(source: Path, packages_path: Path) -> list[dict[str, object]]:
    document = tomllib.loads(source.read_text())
    package_document = tomllib.loads(packages_path.read_text())
    known_packages = set(package_document.get("packages", {}))
    raw_pages = document.get("pages")
    if not isinstance(raw_pages, list) or not raw_pages:
        raise ValueError("manual source must contain at least one [[pages]] entry")

    pages: list[dict[str, object]] = []
    seen_ids: set[str] = set()
    for index, raw in enumerate(raw_pages):
        if not isinstance(raw, dict):
            raise ValueError(f"page {index} must be a table")
        page = dict(raw)
        for field in ("id", "title", "section", "summary", "keywords", "contract"):
            value = page.get(field)
            if not isinstance(value, str) or not value.strip():
                raise ValueError(f"page {index} has invalid {field}")
            page[field] = value.strip()

        page_id = str(page["id"])
        if not ID_RE.fullmatch(page_id):
            raise ValueError(f"invalid manual page id: {page_id}")
        if page_id in seen_ids:
            raise ValueError(f"duplicate manual page id: {page_id}")
        seen_ids.add(page_id)

        aliases = page.get("aliases", [])
        if not isinstance(aliases, list) or not all(
            isinstance(alias, str) and ID_RE.fullmatch(alias.strip())
            for alias in aliases
        ):
            raise ValueError(f"{page_id}: aliases must be valid topic names")
        page["aliases"] = [alias.strip() for alias in aliases]

        packages_any = page.get("packages_any", [])
        if not isinstance(packages_any, list) or not all(
            isinstance(package, str) and package for package in packages_any
        ):
            raise ValueError(f"{page_id}: packages_any must contain package IDs")
        unknown = sorted(set(packages_any) - known_packages)
        if unknown:
            raise ValueError(f"{page_id}: unknown packages: {', '.join(unknown)}")
        page["packages_any"] = packages_any

        body = page.get("body")
        if body is None:
            body = default_body(page)
        if not isinstance(body, str) or not body.strip():
            raise ValueError(f"{page_id}: body must be non-empty")
        page["body"] = body.strip() + "\n"
        pages.append(page)

    seen_names: dict[str, str] = {}
    for page in pages:
        page_id = str(page["id"])
        for name in [page_id, *page["aliases"]]:
            folded = str(name).casefold()
            owner = seen_names.get(folded)
            if owner is not None:
                raise ValueError(
                    f"manual topic name {name} is shared by {owner} and {page_id}"
                )
            seen_names[folded] = page_id
    return pages


def render(pages: list[dict[str, object]], source: Path) -> str:
    lines = [
        "/* Generated by scripts/generate_manual.py. Do not edit. */",
        f"/* Source: {source.name} */",
        "#pragma once",
        "",
        "static const solar_os_manual_page_t SOLAR_OS_MANUAL_GENERATED_PAGES[] = {",
    ]
    for page in pages:
        packages = list(page["packages_any"])
        if packages:
            lines.append("#if " + " || ".join(package_macro(package) for package in packages))
        aliases = "\n".join(page["aliases"])
        lines.extend(
            [
                "    {",
                f"        .id = {c_string(str(page['id']))},",
                f"        .title = {c_string(str(page['title']))},",
                f"        .section = {c_string(str(page['section']))},",
                f"        .summary = {c_string(str(page['summary']))},",
                f"        .aliases = {c_string(aliases)},",
                f"        .keywords = {c_string(str(page['keywords']))},",
                f"        .body = {c_string(str(page['body']))},",
                f"        .contract = {c_string(str(page['contract']))},",
                "    },",
            ]
        )
        if packages:
            lines.append("#endif")
    lines.extend(
        [
            "};",
            "",
            "#define SOLAR_OS_MANUAL_GENERATED_PAGE_COUNT \\",
            "    (sizeof(SOLAR_OS_MANUAL_GENERATED_PAGES) / \\",
            "     sizeof(SOLAR_OS_MANUAL_GENERATED_PAGES[0]))",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=Path)
    parser.add_argument("--packages", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    pages = load_pages(args.input, args.packages)
    output = render(pages, args.input)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if not args.output.exists() or args.output.read_text() != output:
        args.output.write_text(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
