name: Build Elecrow CrowPanel ESP32-S3 4.2 E-paper

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_build-board.yml
    with:
      environment: elecrow_crowpanel_esp32_s3_4_2_epaper
