name: Build ESP32-S3 DevKitC-1 N16R8

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_build-board.yml
    with:
      environment: esp32_s3_devkitc1_n16r8
